services:
  backend:
    build: ./backend
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./instance:/instance

  bot:
    build: ./bot
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - TELEGRAM_TOKEN=TELEGRAM_TOKEN
      - ADMIN_ID=ADMIN_ID
      - BACKEND_API_URL=http://backend:5000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/logs
